# Generated by Django 5.0.3 on 2024-04-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_globals_training_thread_running_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster_records',
            name='word2vec_word_min_count',
        ),
        migrations.AddField(
            model_name='cluster_records',
            name='word2vec_word_min_count_percentage',
            field=models.FloatField(default=0.35),
            preserve_default=False,
        ),
    ]
