# Generated by Django 5.0.3 on 2024-04-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_globals_training_thread_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseTitle',
            field=models.CharField(max_length=350, verbose_name='Course Title'),
        ),
    ]
