# Generated by Django 5.0.3 on 2024-04-21 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_course_coursetitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster_records',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_id'], 'verbose_name': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='job_post',
            options={'ordering': ['-job_id'], 'verbose_name': 'Job Post'},
        ),
    ]
