# Generated by Django 5.0.3 on 2024-04-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0024_alter_job_post_jobdescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-course_id'], 'verbose_name': 'Course'},
        ),
    ]
